#!/usr/bin/env bash
# =============================================================================
# make_pO_datacards.sh  --  generate ALL pO W/Z Combine datacards for one
# channel (muon or electron) into <outdir>.
#
# Consumes the STRUCTURED Combine inputs produced by the analysis repo
#   plotting/mtandmet.C      -> combine_input_W.root  (TDir per fit region)
#   plotting/dileptonpeak.C  -> combine_input_Z.root  (TDir "Z_incl")
# Each region TDirectory holds the 6 absolute templates
#   data_obs / signal / z / ztau / wtau / qcd        (W)
#   data_obs / signal / w / wtau / ztau              (Z)
# All templates are ABSOLUTELY normalized (k_s = A*sigma*L/N_gen) -- no area
# normalization -- so the fit floats real normalizations, not shapes-to-data.
#
# Fit model (per the analysis decisions):
#   * signal           -> POI 'r'  (the per-region W yield strength we extract)
#   * z / ztau / wtau   -> ONE shared rateParam 'ewk_norm' (relative MC
#                          composition LOCKED, only the overall EWK scale floats)
#   * qcd  (ABCD)       -> free rateParam 'qcd_norm' (data-driven, least trusted)
# The combined W+Z card adds a shared 'eff_lumi' (lepton eff x lumi) that
# multiplies BOTH the W signal and the Z signal: the high-purity Z peak pins it
# and it cancels in W/Z ratios -- the "Z as control" simultaneous fit.
#
# Usage:  make_pO_datacards.sh <Wfile_basename> <Zfile_basename> <outdir>
# (the driver copies the two .root inputs into <outdir> first, so datacards
#  reference them by basename and Combine resolves them relative to the card.)
#
# bash-3.2 safe (macOS stock bash): no associative arrays, no 'declare -A'.
# =============================================================================
set -euo pipefail

WFILE="${1:?need W input basename}"
ZFILE="${2:?need Z input basename}"
OUTDIR="${3:?need output dir}"
mkdir -p "$OUTDIR"

# ---- W single-region datacard (one fit region = one Combine channel) --------
gen_W_card() {
  R="$1"                       # region/channel label == TDirectory name
  cat > "$OUTDIR/datacard_${R}.txt" <<EOF
# Auto-generated by make_pO_datacards.sh -- W region '${R}', MET discriminant.
imax 1
jmax 4
kmax *
------------
shapes data_obs ${R} ${WFILE} ${R}/data_obs
shapes signal   ${R} ${WFILE} ${R}/signal
shapes z        ${R} ${WFILE} ${R}/z
shapes ztau     ${R} ${WFILE} ${R}/ztau
shapes wtau     ${R} ${WFILE} ${R}/wtau
shapes qcd      ${R} ${WFILE} ${R}/qcd
------------
bin          ${R}
observation  -1
------------
bin      ${R}      ${R}    ${R}    ${R}    ${R}
process  signal    z       ztau    wtau    qcd
process  0         1       2       3       4
rate     -1        -1      -1      -1      -1
------------
# ALL MC (signal + EWK z/ztau/wtau) share ONE normalization = the POI 'r':
# the relative composition is FIXED by the absolute k_s cross-section templates,
# only the overall MC scale floats. 'signal' (index 0) is scaled by r; reusing
# the name 'r' as a rateParam ties the EWK backgrounds to that SAME r.
r        rateParam ${R} z    1
r        rateParam ${R} ztau 1
r        rateParam ${R} wtau 1
# Data-driven ABCD QCD: its own free normalization.
qcd_norm rateParam ${R} qcd  1 [0,10]
EOF
}

# ---- Z inclusive standalone datacard ----------------------------------------
gen_Z_card() {
  cat > "$OUTDIR/datacard_Z_incl.txt" <<EOF
# Auto-generated -- Z inclusive (dilepton mass peak discriminant).
imax 1
jmax 3
kmax *
------------
shapes data_obs Z_incl ${ZFILE} Z_incl/data_obs
shapes signal   Z_incl ${ZFILE} Z_incl/signal
shapes w        Z_incl ${ZFILE} Z_incl/w
shapes wtau     Z_incl ${ZFILE} Z_incl/wtau
shapes ztau     Z_incl ${ZFILE} Z_incl/ztau
------------
bin          Z_incl
observation  -1
------------
bin      Z_incl    Z_incl  Z_incl  Z_incl
process  signal    w       wtau    ztau
process  0         1       2       3
rate     -1        -1      -1      -1
------------
# ALL Z MC (signal + w/wtau/ztau) share ONE normalization = the POI 'r'
# (relative composition fixed by the absolute cross sections).
r rateParam Z_incl w    1
r rateParam Z_incl wtau 1
r rateParam Z_incl ztau 1
EOF
}

# ---- Combined W_incl + Z_incl simultaneous datacard -------------------------
# Two channels.  POI 'r' scales ONLY the W signal (process index 0).  The Z
# signal is renamed 'zsig' (index >=1, NOT a POI) and is scaled solely by the
# shared 'eff_lumi'.  eff_lumi multiplies BOTH 'signal' (W) and 'zsig' (Z); the
# Z peak (~100% zsig) pins it, propagating the lepton-eff x lumi constraint to W.
gen_WZ_combined_card() {
  cat > "$OUTDIR/datacard_WZ.txt" <<EOF
# Auto-generated -- simultaneous W(incl) + Z(incl) fit, shared eff_lumi.
imax 2
jmax *
kmax *
------------
shapes data_obs Wincl ${WFILE} W_incl/data_obs
shapes signal   Wincl ${WFILE} W_incl/signal
shapes z        Wincl ${WFILE} W_incl/z
shapes ztau     Wincl ${WFILE} W_incl/ztau
shapes wtau     Wincl ${WFILE} W_incl/wtau
shapes qcd      Wincl ${WFILE} W_incl/qcd
shapes data_obs Zincl ${ZFILE} Z_incl/data_obs
shapes zsig     Zincl ${ZFILE} Z_incl/signal
shapes w        Zincl ${ZFILE} Z_incl/w
shapes wtau     Zincl ${ZFILE} Z_incl/wtau
shapes ztau     Zincl ${ZFILE} Z_incl/ztau
------------
bin          Wincl   Zincl
observation  -1      -1
------------
bin      Wincl    Wincl   Wincl   Wincl   Wincl    Zincl   Zincl   Zincl   Zincl
process  signal   z       ztau    wtau    qcd      zsig    w       wtau    ztau
process  0        1       2       3       4        5       6       7       8
rate     -1       -1      -1      -1      -1       -1      -1      -1      -1
------------
# Shared lepton-eff x lumi scale on ALL MC in BOTH channels (signal + every MC
# background): fixes the relative MC composition; the high-purity Z peak pins it.
eff_lumi  rateParam * signal 1 [0,5]
eff_lumi  rateParam * zsig   1 [0,5]
eff_lumi  rateParam Wincl z  1 [0,5]
eff_lumi  rateParam Zincl w  1 [0,5]
eff_lumi  rateParam * wtau   1 [0,5]
eff_lumi  rateParam * ztau   1 [0,5]
# W cross-section deviation: the POI 'r' is an EXTRA scale on the W signal only
# (signal index 0 -> scaled by r*eff_lumi). Data-driven QCD: its own free param.
qcd_norm  rateParam Wincl qcd 1 [0,10]
EOF
}

# ---- generate everything ----------------------------------------------------
n=0
for C in Wp Wm; do
  for B in lab fb; do
    for iy in $(seq 0 11); do
      gen_W_card "${C}_${B}_y${iy}"; n=$((n+1))
    done
  done
  gen_W_card "${C}_incl"; n=$((n+1))
done
gen_W_card "W_incl";       n=$((n+1))
gen_Z_card;                n=$((n+1))
gen_WZ_combined_card;      n=$((n+1))

echo "[make_pO_datacards] wrote ${n} datacards to ${OUTDIR}"
